var description = "All questions are fill in the blank. For multiple fill in the blanks, use a comma followed by a space to separate answers ex:( two, five, ten )"

var QA = [
	["The extension for a Java source file is  ________________.",".java"],
	["Developing apps that are appropriate for different locales is known as ________________.","localization"],
	["Android can be used to develop which types of apps ________________.","Photography, Reference, Finance"],
	["When an IDE builds a project, it puts the .dex files and the rest of the files for the project in an ________________.","Android package"],
	["When the IDE builds a project, it compiles the ________________ into ________________ and then into________________.","Java source code (.java files), Java bytecodes (.class files), Dalvik executable files (.dex files)"],
	["________________ lets your IDE communicate with an emulator or physical Android device.","The Android Debug Bridge (ADB)"],
	["Dalvik executable files (.dex files) can be run by the ________________.","Dalvik virtual machine"],
	["Android is a/an ________________ -based operating system.","linux"],
	["The extension for a Java bytecode file is ________________.",".class"],
	["True or False: Android is a Linux-based operating system designed primarily for touchscreen mobile devices. Android code is open source. Android is designed for smartphones and tablets.","true"],
	["The EditText element displays the widget that allows the user to enter text. This widget can be referred to as a/an ________________.","editable text view"],
	["A ________________ contains all of the files for an app including the files for the Java source code.","project"],
	["The display text for an app is typically stored in the ^^ ________________ file.","strings.xml"],
	["SDK stands for ________________.","Software Development Kit"],
	["For security reasons, all Android apps must be digitally ________________ with a certificate.","signed"],
	["True or False: An Android package (.apk) file contains: Compiled resources, Uncompiled resources, .dex files.","true"],
	["________________ is a container that determines where child elements are displayed on a screen.","layout"],
	["In Android, controls are typically referred to as ________________.","widgets"],
	["Native libraries in the Android stack are written in ________________.","C"],
	["An example of an IDE (Integrated Development Environment) is ________________.","Android Studio"],
	["________________ is an organization devoted to advancing open standards for mobile devices.","Open Handset Alliance"],
	["________________ is an XML file that specifies the first activity to launch when the app is started.","AndroidManifest.xml"],
	["An on-screen keyboard is also known as a ________________.","soft keyboard"],
	["An Android Virtual Device (AVD) is an ________________.","emulator"],
	["The Android system architecture is also known as the Android ________________.","stack"],
	["________________ is not part of the Android stack.","Android Software Development Kit (SDK)"],
	["________________ is named after something sweet and corresponds with an Application Programming Interface (API) number.","Any major release of Android"],
	["If the Hardware Keyboard option is not enabled for an emulator you can use the ________________ to enter text.","soft keyboard"],
	["It is a best practice to use ________________ for padding because, it allows your app to scale properly on various devices.","density-independent pixels (dp)"],
	["You can use Android to develop apps for ________________ mobile devices such as smartphones and tablet computers.","touchscreen"]
];

